### ISSUE TITLE
Using sqlite in WAL mode causes file saving failure when used on JupyterHub on NFS

### ISSUE THREAD

**Issue by yuvipanda** [jupyter-server/jupyter_server_fileid#60]
## Description

We upgraded from lab 3.5 to 3.6, and that seems to have brought this dependency in. At startup, it seems to try to open a sqlite db in WAL mode under `~/.local/share/jupyter`, which is on NFS. This fails intermittently, as sqlite's WAL mode is not supported on NFS. https://www.sqlite.org/wal.html states:

> All processes using a database must be on the same host computer; WAL does not work over a network filesystem. 

So on server startup, this fails with these log messages:

```
[I 2023-02-22 14:05:52.993 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-02-22 14:05:52.993 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/jovyan
[I 2023-02-22 14:05:52.993 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/jovyan/.local/share/jupyter/file_id_manager.db
[I 2023-02-22 14:05:53.009 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-02-22 14:05:53.009 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices.
[W 2023-02-22 14:05:53.096 SingleUserLabApp manager:359] jupyter_server_fileid | extension failed loading with message: unable to open database file
[E 2023-02-22 14:05:53.096 SingleUserLabApp manager:360] jupyter_server_fileid | stack trace
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 355, in load_extension
        extension.load_all_points(self.serverapp)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 229, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 229, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 222, in load_point
        return point.load(serverapp)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 148, in load
        return loader(serverapp)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 453, in _load_jupyter_server_extension
        extension.initialize()
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 420, in initialize
        self._prepare_settings()
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 302, in _prepare_settings
        self.initialize_settings()
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_fileid/extension.py", line 23, in initialize_settings
        file_id_manager = self.file_id_manager_class(
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_fileid/manager.py", line 244, in __init__
        self.con.execute("PRAGMA journal_mode = WAL")
    sqlite3.OperationalError: unable to open database file
```

Unfortunately, this means *all* file save operations via contentsmanager fail! So this is in the critical path for all file saves, new notebook creations, etc - even when not using RTC.

```
[E 2023-02-22 14:09:35.383 SingleUserLabApp web:1798] Uncaught exception GET /user/<name>/api/contents/KMeans_Tutorial.ipynb?type=notebook&_=1677092974636 (10.1.0.10)
    HTTPServerRequest(protocol='https', host='jupyter.utoronto.ca', method='GET', uri='/user/<name>/api/contents/KMeans_Tutorial.ipynb?type=notebook&_=1677092974636', version='HTTP/1.1', remote_ip='10.1.0.10')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 116, in get
        self.contents_manager.get(
      File "/opt/conda/lib/python3.10/site-packages/jupytext/contentsmanager.py", line 207, in get
        model = self.super.get(path, content, type="notebook", format=format)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 424, in get
        model = self._notebook_model(path, content=content)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 372, in _notebook_model
        nb = self._read_notebook(
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 267, in _read_notebook
        with self.open(os_path, "r", encoding="utf-8") as f:
      File "/opt/conda/lib/python3.10/contextlib.py", line 135, in __enter__
        return next(self.gen)
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 198, in open
        with open(os_path, *args, **kwargs) as f:
    OSError: [Errno 121] Remote I/O error: '/home/jovyan/KMeans_Tutorial.ipynb'
```

We have reverted to JupyterLab 3.5 in the meantime.

## Questions

1. Is fileid required even when not using RTC?
2. Does the db need to persist *across* JupyterHub sessions? if not, we can put it in /tmp (like in https://github.com/2i2c-org/infrastructure/pull/2246).
3. Does it need the WAL? Based on https://github.com/jupyter-server/jupyter_server_fileid/blob/99c183064f948279ed7ecda8d033786a4cee8ca8/jupyter_server_fileid/manager.py#L243 that looks like an intentional decision. If so, this would cause lots of problems on NFS

**Comment by dlqqq** [comment]
Very sorry to hear that you're running into compatibility issues. I wasn't aware that the WAL journal mode fails on NFS.

> Is fileid required even when not using RTC?

Not at the moment, though there are plans to build new extensions that depend on fileid.

> Does the db need to persist across JupyterHub sessions? if not, we can put it in /tmp (like in https://github.com/2i2c-org/infrastructure/pull/2246).

cc @fcollonval 

Well, it depends on the extensions that are using fileid. If RTC is persisting the fileids in their own persistent store (which I believe they do, but am not certain of this), then the fileid database also must be persisted. Otherwise, no.

> Does it need the WAL?

It's required when separate threads and processes are calling FileIdManager methods. Otherwise, database reads in the main process block writes in other processes. 

However, I don't think it's required just for a fresh JupyterLab 3.6.x instance to work with RTC. The most obvious solution for NFS support is to make the WAL journal mode a configurable defaulting to `False`.

This issue may be remedied by migrating away from using sqlite directly and instead opting for aiosqlite, which should handle this case on its own. Assuming aiosqlite doesn't require the WAL journal mode, we can preserve functionality for the multi-process case, while supporting NFS.

**Comment by yuvipanda** [comment]
> The most obvious solution for NFS support is to make the WAL journal mode a configurable defaulting to `False`.

+1, I think this would be helpful in preventing issues for other JupyterHub users as they migrate to JupyterLab 3.6! We found it pretty quick but might be more difficult and frustrating for others, as this dependency comes through quite a few layers :) 

I appreciate all the work on this! \o/

**Comment by kevin-bates** [comment]
I was writing this up when these responses came in. Rather than on or off, would it make sense to provide different defaults based on the configured class and allow all values (via configuration)?

> Hi @yuvipanda - I agree that `WAL` is the wrong value for the `ArbitraryFileIdManager` journal mode given this class is supposed to be file-system agnostic.
>
> Seems like a `db_journal_mode` trait is desirable here with the default for `ArbitraryFileIdManager` being `DELETE` (i.e., default journal mode) and the default for `LocalFileIdManager` being `WAL` - which is already file-system sensitive.  This way operators/admins can "tune" their transaction journaling however they like but OOTB values "just work".

**Comment by dlqqq** [comment]
If I cut a new release of `jupyter_server_fileid` to revert the default journal mode, where does the target version need to be bumped? IOW, in which of the JupyterLab transitive dependencies is `jupyter_server_fileid` explicitly listed in `pyproject.toml`?

**Comment by dlqqq** [comment]
@kevin-bates 

> Rather than on or off, would it make sense to provide different defaults based on the configured class and allow all values (via configuration)?

Yes, that seems very reasonable. My apologies, I didn't get as much coffee today as I should have.

**Comment by dlqqq** [comment]
The main idea is that the default should not be the WAL journal mode however. I think we should try to support NFS out-of-the-box given the popularity of JupyterHub.

**Comment by kevin-bates** [comment]
>> Rather than on or off, would it make sense to provide different defaults based on the configured class and allow all values (via configuration)?

> Yes, that seems very reasonable. My apologies, I didn't get as much coffee today as I should have.

> The main idea is that the default should not be the WAL journal mode however. I think we should try to support NFS out-of-the-box given the popularity of JupyterHub.

OK - even with `LocalFileIdManager`?  (So `DELETE` is the default for both classes?)

I ask for clarification because your previous comments contradict each other.  Seems like the default for `LocalFIleIdManager` could still be `WAL` given it is not the default class and its use is opt-in.

**Comment by dlqqq** [comment]
Good observation. Yes, that's also reasonable. To summarize: the next steps would be to make journal mode configurable, default to `DELETE` for `ArbitraryFIDM` and `WAL` for `LocalFIDM`.

**Comment by dlqqq** [comment]
This change should be fairly straight-forward. I'm currently really busy trying to get an initial release of Jupyter AI setup; can anybody else own this? If not, I can still tackle this by the end of the week.

**Comment by kevin-bates** [comment]
I can go ahead and toss this in.

Regarding the dependency resolution/mystery...

It turns out that the package `jupyter_server_ydoc` is what is pulling in fileID.  However, it also appears that `jupyter_server_ydoc` has been both _moved_ and _renamed_ from the juptyer-server org to the jupyterlab org and is now called `juptyerlab/jupyter_collaboration` which can be inferred from the [releases](https://github.com/jupyterlab/jupyter_collaboration/releases) page.

**Comment by kevin-bates** [comment]
> Unfortunately, this means all file save operations via contentsmanager fail! So this is in the critical path for all file saves, new notebook creations, etc - even when not using RTC.

@yuvipanda - I'm not immediately seeing the connection between this issue and the general failures to persist content from the included stack trace.  Could you please shed light on how the inability to initialize the fileID manager interferes with opening a notebook file?

**Comment by dlqqq** [comment]
@yuvipanda Can you try installing the fileid 0.8.0 release manually and see if this fixes your issue?

**Comment by yuvipanda** [comment]
@kevin-bates i did a little more digging, and unfortunately I couldn't find any logs indicating that file_id stuff is actually in the critical path for file saves. I did find stacktraces implicating the signatures database though (https://github.com/2i2c-org/infrastructure/issues/2245#issuecomment-1444602512), so perhaps that is to blame and not this?

Regardless, I think not using WAL on NFS is still the right call, but perhaps this is not as serious as I had feared. Thank you for digging in!

@dlqqq I'm going to be on vacation for a couple of weeks so won't really be able to do much until I'm back.

**Comment by kevin-bates** [comment]
>  I couldn't find any logs indicating that file_id stuff is actually in the critical path for file saves.

Thanks for the update @yuvipanda - no worries, pure curiosity on my part (always trying to gain information).

> I did find stacktraces implicating the signatures database though (https://github.com/2i2c-org/infrastructure/issues/2245#issuecomment-1444602512), so perhaps that is to blame and not this?

Interesting.  Looking at `nbformat`'s use of SQLite, I see that it doesn't specify the `journal_mode` PRAGMA, but, as you state on that issue, the `nbsignatures.db` is on NFS, which implies that making the default `journal_mode` for `ArbitraryFileIdManager` default to `DELETE` isn't going to help if there's a general SQLite vs. NFS conflict any way.

> Regardless, I think not using WAL on NFS is still the right call

Totally agree - making it completely configurable is more correct, but we may have other NFS-related battles per what we see in `nbformat`.

(Have a great vacation! 🌴)
