### ISSUE TITLE
UNIQUE constraint failed when moving file

### ISSUE THREAD

**Issue by dleen** [jupyter-server/jupyter_server_fileid#62]
## Description

Creating a file in Jupyter, then moving it using `mv`, and finally renaming the moved file from Jupyter does not work.

It seems like there needs to be a sync of some sort before doing the move...

## Reproduce

0. Use `LocalFileIdManager`.
1. Create notebook `foo1.ipynb`
2. Open sqlite db: `sqlite3 /Users/dleen/Library/Jupyter/file_id_manager.db`
3. Verify file is indexed: 
```
SELECT * FROM Files;
4462c993-1a32-4a29-93b6-e14325a57cd1|/Users/dleen/code/catalog/foo1.ipynb|91561383|1680642664149532160|1680739962758658767|0
```
4. Outside of Jupyter move the file: `mv foo1.ipynb foo2.ipynb`
5. In Jupyter close `foo1.ipynb` if it was still open, and open `foo2.ipynb`.
6. Rename `foo2.ipynb` to `foo3.ipynb`.
7. See error in log:
```
[E 2023-04-05 17:13:02.255 ServerApp] UNIQUE constraint failed: Files.ino
```
8. In sqlite no new entry has been created.

## Expected behavior

The file is correctly indexed and preserves the id of `foo1.ipynb`:
```
SELECT * FROM Files;
4462c993-1a32-4a29-93b6-e14325a57cd1|/Users/dleen/code/catalog/foo3.ipynb|91561383|1680642664149532160|1680739962758658767|0
```

**Comment by dleen** [comment]
cc @dlqqq

**Comment by dleen** [comment]
The problem arises because the out of band `mv` changes the path which means that an entry in the DB corresponding to old path does not exist: https://github.com/jupyter-server/jupyter_server_fileid/blob/main/jupyter_server_fileid/manager.py#L810. This tries to create a new entry (instead of updating the existing one) which fails due to the uniqueness constraint on the inode number.

**Comment by dleen** [comment]
It's almost as if we need to call `FIM._sync_file` after the `mv` has been done but somehow before the contents manager moves the file as once we enter the `FIM.move` method we've lost track of original value of `old_path`.

## Example:
`foo1.ipynb` - indexed in DB

`mv foo1.ipynb foo2.ipynb` - but `foo2.ipynb` is not indexed. DB still contains `foo1.ipynb`.

Back in Jupyter using contents manager to do a rename: `foo2.ipynb -> foo3.ipynb`. Thus the check in the DB for the old path `foo2.ipynb` fails. The `ino` is the same though but I'm not sure if this can be relied on as the proof of identity.

The way this could work as is, is if somehow the DB was updated to include `foo2.ipynb` in the DB before `move` is called.

**Comment by dlqqq** [comment]
@dleen Are you using `ArbitraryFileIdManager` or `LocalFileIdManager`?

`LocalFileIdManager` (for **local** filesystems) is the one that can track out-of-band moves (e.g. `mv`). However, we default to `ArbitraryFileIdManager` (for **arbitrary** filesystems, which may not have the file metadata retrieved via POSIX `stat()`) to preserve platform compatibility.

**Comment by dleen** [comment]
I'm using `LocalFileIdManager` - sorry thought I had mentioned that somewhere

**Comment by dlqqq** [comment]
@dleen Are you using JL in collaborative mode?

**Comment by dleen** [comment]
No, just launching via:
```
jupyter lab . --FileIdExtension.file_id_manager_class=jupyter_server_fileid.manager.LocalFileIdManager
```

```
jupyter lab --version
3.6.3
```

**Comment by kevin-bates** [comment]
Perhaps in `move()` you could call `get_id(old_path)` just after stat-ing `new_path`?  The `id` returned from `get_id(old_path)` could then supplant the `SELECT` statement to get the ID, but, at this point, you know that ID and PATH have a record behind them.
