### ISSUE TITLE
How to deal with file deletion?

### ISSUE THREAD

**Issue by dleen** [jupyter-server/jupyter_server_fileid#67]
## Problem

Imagine that we are building a system that allows users to add comments on a notebook. The comments are stored in a backend system hosted in the cloud.

The user creates a notebook. The user uses the commenting UI to add a comment and clicks submit. The following happens:

0. The newly created notebook is indexed via the `save` method of `FIM` (caveat: see issue #66)
1. The commenting extension UI sends the notebook path to the Jupyter server.
2. The commenting extension backend code calls `FIM.get_id(path)` (assuming the file was successfully indexed) to get the associated `id` of the notebook.
3. The commenting extension submits a request to the backend system to store the comment using the `id` retrieved from the `FIM`.

### Deletion scenario

1. The user deletes a notebook which has associated comments.
2. The commenting extension code subscribes to the contents manager `delete` event.
3. The FileID manager extension also subscribes to the contents manager `delete` event.

I don't know for sure but but it seems fair that we cannot assume which subscriber is triggered first. There are potentially two cases:

4. The FileID manager is triggered first. The record of the notebook is deleted from the sqlite DB.
5. The commenting extension calls `FIM.get_id(path)` which returns `None`. The extension does not know which record to delete from the commenting backend system.

OR

4. The commenting extension calls `FIM.get_id(path)` which returns the `id`. The extension deletes the corresponding record from the commenting backend system.
5. The FileID manager is triggered and the record of the notebook is deleted from the sqlite DB.

### Solutions?

Alternatively, we could implement a custom contents manager which calls `FIM.get_id(path)` potentially before the event is emitted. However this does not seem like a long term maintainable solution due to the dependency on when the event is emitted.

Another solution could be for the FileID manager to emit an event for `moves/save/deletes` with a corresponding `id` so that extensions using the `id`s can react to changes.

One other solution could be to use "soft" deletes where the row in the DB is "flagged" as deleted but kept in the DB.

### Discussion

Or is it possible that there's a simpler solution here?

**Comment by dlqqq** [comment]
@dleen I think the simplest way would be to allow users to configure what events a FIM listens to. That way, you can disable the FIM from listening to `delete` events from the CM, call `get_id(<path>)` and delete the associated commenting data, and then call `FIM.delete()` yourself (since all event listeners are public methods anyways).

This would be a pretty simple change to implement, do you want to give it a try? We use [`traitlets.config`](https://traitlets.readthedocs.io/en/stable/config.html) to implement configurability of our classes. You would want to define a new trait that accepts a list that defines the CM event actions the class will listen to, say `self.cm_actions`. This trait should default to listening to all the actions, e.g. default to the value `["get", "save", "rename", "copy", "delete"]`. Then, you would want to change the logic of the below method to bind the action to `None` if the action isn't listed in `self.cm_actions`.

```
def get_handlers_by_action(self) -> Dict[str, Optional[Callable[[Dict[str, Any]], Any]]]:
    return {
        "get": None,
        "save": lambda data: self.save(data["path"]),
        "rename": lambda data: self.move(data["source_path"], data["path"]),
        "copy": lambda data: self.copy(data["source_path"], data["path"]),
        "delete": lambda data: self.delete(data["path"]),
    }
```

**Comment by kevin-bates** [comment]
Specifically tuning FIM's event listener works fine if your application is the only server extension in town.  However, if other server extensions expect, in this case, "delete" events, they'll be screwed.

Seems like @dleen's suggestion of FIM _emitting_ events (`index`, `move`, `delete`, `copy`?) and letting _each_ server extension determine which events are pertinent is a good way to go.  This eliminates the ambiguity of which listener acts first on the same event and doesn't interfere with multiple server extension configurations.

**Comment by dlqqq** [comment]
@kevin-bates I'm not quite sure I follow. Dependent extensions need to be able to query for the file ID **before** the FIM deletes the record, not before. Emitting an event in the FIM methods to allow extensions to respond **after** deletion doesn't seem to solve @dleen 's issue.

**Comment by dleen** [comment]
The deletion event would include the ID of the file deleted which would probably work

**Comment by kevin-bates** [comment]
Correct.  All you (@dleen) need is the ID.  This way the ambiguity is resolved.  All events emitted by the FIM would include the corresponding ID(s).

**Comment by dlqqq** [comment]
Ah, thank you both for clarifying. Then yes, we could implement support for this.

(btw I'm insanely busy with [Jupyter AI](https://github.com/jupyterlab/jupyter-ai), so I'd love to accept open source contributions for any of the issues opened recently, just reach out to me so I can assign you 🤗)

**Comment by dleen** [comment]
Yes I'm willing to work on these issues - just wanted to discuss before jumping into the code
