### ISSUE TITLE
Allow db_path to be set to ":memory:"

### ISSUE THREAD

**Issue by cmd-ntrf** [jupyter-server/jupyter_server_fileid#69]
### Problem

Some network filesystems (e.g.: NFS, Lustre) do not handle well SQLite database transactions and it can cause serious hanging issue when creating and making transaction on the database when it resides on these filesystems. This results in a poor Jupyter user experience: timeouts, error 504, etc.

Similar issues have been reported for IPython in the past:
- https://github.com/ipython/ipython/issues/11678
- https://github.com/ipython/ipython/issues/882

### Proposed Solution

When validating `BaseFileIdManager.db_path`, allow the string to be either an absolute path or `":memory:"`.

This solution is implemented in different Jupyter subprojects:
- [NotebookNotary.db_file](https://github.com/jupyter/nbformat/blob/0a2942c8f77d33b43a327293c7a7596afcf4527d/nbformat/sign.py#L373)
- [IPython.HistoryAccessor.hist_file](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.history.html#IPython.core.history.HistoryAccessor.hist_file)

I have implemented the solution in the PR #70 with the same title as this issue.

### Additional context

Furthermore, to be more consistent with other Jupyter projects, I would recommend:
1. the parameter be renamed `db_file` instead of `db_path`. 
2. the default parameter value be handled by the "@default" decorated function, like what is done for [`NotebookNotary.db_file`](https://github.com/jupyter/nbformat/blob/0a2942c8f77d33b43a327293c7a7596afcf4527d/nbformat/sign.py#L380) instead of a global variable at the module level.

**Comment by dlqqq** [comment]
@cmd-ntrf Thank you for these great suggestions! I will incorporate these in the next release, which I will implement when I get an opportunity.

**Comment by Zsailer** [comment]
Fixed in #70. Once #72 gets merged, I can cut a release with these changes. Thanks @cmd-ntrf for the contribution!
